#!/bin/bash
echo "bashbot: a simple bot written almost entirely in bash."
echo "You can find the source at https://github.com/XCaminhante/bashbot"

[ -d .git ] && {
   echo -n "... working directory currently at commit ";
   git rev-parse HEAD
}
